Silence pytest warning
rhinstaller/dasbus pull request #42
Opened 2020-09-12 10:47 UTC by z3ntu

```
tests/test_connection.py:34
  /tmp/dasbus/tests/test_connection.py:34: PytestCollectionWarning: cannot collect test class 'TestMessageBus' because it has a __init__ constructor (from: tests/test_connection.py)
    class TestMessageBus(MessageBus):
```

2020-09-22 11:56 UTC, poncovka commented
The errors should be fixed by https://github.com/rhinstaller/dasbus/pull/43 now.

2020-09-22 12:01 UTC, poncovka requested changes
Thanks for your pull request! However, I suggest another solution.

2020-09-22 19:36 UTC, z3ntu commented on tests/test_connection.py
> +    __test__ = False
done, I used `MockMessageBus` which fits better imo

2020-09-23 10:25 UTC, poncovka commented
/packit build

2020-09-23 12:39 UTC, jkonecny12 approved these changes
Looks good to me too!

2020-09-23 16:56 UTC, poncovka approved these changes
Looks good to me. Thanks!

2020-09-23 16:58 UTC, merged